### PR TITLE
Add disposition option to attachment_url for forcing file downloads

### LINKED ISSUE #118: Creating a forced download link
This might be a super basic question but it's late and I'm stumped. I'm using Refile to serve up audio files uploaded by musicians:

``` ruby
class Song < ActiveRecord::Base
  attachment :audio_file
end
```

I'm also storing the _filename _size _content_type rows in my songs table

I want to create a link so that when someone clicks it, it automatically downloads. Currently, I can get it to open streaming via attachment_url, but not the equivalent of "save target as". I'm not sure how to serve this out from the controller in a send_file, either.

``` ruby
#View
  <%= link_to "download", attachment_url(song, :audio_file, filename: song.audio_file_filename)%>  #opens up an mp3 player
  <%= link_to "controller download ", user_album_song_download_path(current_user, @album, song) %> 

#controller - not sure what to do here, either
  def download
    send_file Refile.attachment_url(@song, :audio_file), type: @song.audio_file_content_type, disposition: :attachment
  end
```

Where am I going wrong, and is this in the documentation anywhere?

### PR DESCRIPTION
**Pull request by excid3**
Add option for requesting a file with the `disposition: "attachment"`.

This fixes #118

### CODE REVIEW

**Comment by jnicklas** [comment]
Using query strings for this is a bit problematic, since we heavily encourage use of CDNs. CloudFront has query strings disabled by default, for performance reasons, some CDNs might not support query strings at all.

**Comment by excid3** [comment]
Oh dang. Good point. What's a better way to solve this?

**Comment by jnicklas** [comment]
See also #91, btw.

The solution is to put it into the URL. But it's *another* thing we need to put there. Since there are a number of people asking for this, we should fix this somehow. IMO it would make the most sense to put this at the beginning of the URL. As in `/inline/cache/12345/test.jpg` or something like that. We should let `Refile.attachment_url` fill this in as `inline` by default, so it doesn't have to be specified when we don't care about it.

I'm a bit torn on the name though. `Content-Disposition: inline` makes sense, but the word `inline` in of itself doesn't really communicate what it's trying to do.

**Comment by excid3** [comment]
Well, I just found the `download` HTML5 attribute that makes links download the request instead of navigating to it. I think we can safely skip adding a disposition option into Refile and just recommend using that.

I can submit a PR for a Readme update if you want.

**Comment by jnicklas** [comment]
Browser support is a bit shaky, it seems.

**Comment by jnicklas** [comment]
Closing this PR for now. Let's move discussion back to #118.

**Pull request closed without merging**
